### ISSUE TITLE
Newtonsoft.JSON.dll plus RepzScreenshot.pfx missing

### ISSUE THREAD

**Issue by Bluscream** [tccr/Repz-Screenshot#1]
Error	1	Unable to get MD5 checksum for the key file "RepzScreenshot.pfx". Could not find file 'D:\Coding\Projekte\RepZ\RepzScreenshot\RepzScreenshot\RepzScreenshot.pfx'.	RepzScreenshot

I manually downloaded the DLL to to fix the warning but i still need the pfx file

**Comment by tccr** [comment]
Open the project properties and uncheck `Sign ClickOnce-Manifests` and `Sign Assembly` on the Signing tab.
Seems to be working.
