### ISSUE TITLE
[Request] Copy Report in Markdown Format

### ISSUE THREAD

**Issue by Bluscream** [tccr/Repz-Screenshot#11]
Hey Mark,

Some websites like the [NBS clan website](www.nbsclan.org/forum/) only allow markdown instead of BBCode so it would be cool to have a button to copy it in markdown aswell :)

**Comment by tccr** [comment]
Already saw your reports there, I'll add this.

**Comment by Bluscream** [comment]
Thanks :+1:

**Comment by Bluscream** [comment]
Implemented!
