### ISSUE TITLE
Alignment bug?

### ISSUE THREAD

**Issue by Bluscream** [tccr/Repz-Screenshot#12]
![1](https://i.gyazo.com/103001d85259a50b1f189656a4a85324.png)
![2](https://i.gyazo.com/c4bc3cfcc64c1bbbc2732d4db1f0a32a.png)

This seems to be buggy :o

**Comment by tccr** [comment]
If you mean the details on the left, then it should be better with 47f288fa38c4e0208aeeb593c6eeb984d036aada. If you mean something else, please describe a bit further because I don't see it.

**Comment by Bluscream** [comment]
Yes i meant the details. Thanks for fixing :D
