### ISSUE TITLE
[Suggestion] Own row for servers/players

### ISSUE THREAD

**Issue by Bluscream** [tccr/Repz-Screenshot#6]
It would be cool if server would not be in the same row as screenshotted players.

I would suggest something like:

ᅠᅠᅠ
ᅠᅠᅠ
ᅠᅠᅠ

```
Search Player | Server Browser || Server 1 | Server 2 | etc...
```
```
Player 1 | Player 2 | etc...
```

**Comment by tccr** [comment]
What do you think about this?

**Comment by Bluscream** [comment]
It's not exactly what i expected, but it's even better :)

But that opens a new suggestion to you,

Can you make the server tabs also colored?

* Uncolored means that everything is okay.
* Green means all players on this server are screenshotted.
* Yellow means that there is a new, unscreenshotted player on the server.
* Red means "Could not connect to the server" or other Errors.

**Comment by tccr** [comment]
Done!
Not exactly as you said:
* Uncolored: There are players on the server which are not screenshotted
* Yellow: Some screenshots are currently loading
* Green: All players were screenshotted without errors
* Red: An error occured

**Comment by Bluscream** [comment]
Love your work :3
